Rails/NameList/config/routes.rb
NameList::Application.routes.draw do
  resources :tops

end

Rails/NameList/app/models/top.rb
class Top < ActiveRecord::Base
end

Rails/NameList/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
#  protect_from_forgery with: :exception
  protect_from_forgery with: :null_session
end

Rails/NameList/app/controllers/tops_controller.rb
class TopsController < ApplicationController
  before_action :set_top, only: [:show, :edit, :update, :destroy]

  # GET /tops
  # GET /tops.json
  def index
    @tops = Top.all
  end

  # GET /tops/1
  # GET /tops/1.json
  def show
  end

  # GET /tops/new
  def new
    @top = Top.new
  end

  # GET /tops/1/edit
  def edit
  end

  # POST /tops
  # POST /tops.json
  def create
    @top = Top.new(top_params)

    respond_to do |format|
      if @top.save
        format.html { redirect_to @top, notice: 'Top was successfully created.' }
        format.json { render action: 'show', status: :created, location: @top }
      else
        format.html { render action: 'new' }
        format.json { render json: @top.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tops/1
  # PATCH/PUT /tops/1.json
  def update
    respond_to do |format|
      if @top.update(top_params)
        format.html { redirect_to @top, notice: 'Top was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @top.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tops/1
  # DELETE /tops/1.json
  def destroy
    @top.destroy
    respond_to do |format|
      format.html { redirect_to tops_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_top
      @top = Top.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def top_params
      params.require(:top).permit(:name)
    end
end

Rails/NameList/app/helpers/application_helper.rb
module ApplicationHelper
end

Rails/NameList/app/helpers/to_ps_helper.rb
module ToPsHelper
end

Rails/NameList/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NameList</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

Rails/NameList/app/views/tops/_form.html.erb
<%= form_for(@top) do |f| %>
  <% if @top.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@top.errors.count, "error") %> prohibited this top from being saved:</h2>

      <ul>
      <% @top.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Rails/NameList/app/views/tops/edit.html.erb
<h1>Editing top</h1>

<%= render 'form' %>

<%= link_to 'Show', @top %> |
<%= link_to 'Back', tops_path %>

Rails/NameList/app/views/tops/index.html.erb
<h1>Listing tops</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @tops.each do |top| %>
      <tr>
        <td><%= top.name %></td>
        <td><%= link_to 'Show', top %></td>
        <td><%= link_to 'Edit', edit_top_path(top) %></td>
        <td><%= link_to 'Destroy', top, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Top', new_top_path %>

Rails/NameList/app/views/tops/new.html.erb
<h1>New top</h1>

<%= render 'form' %>

<%= link_to 'Back', tops_path %>

Rails/NameList/app/views/tops/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @top.name %>
</p>

<%= link_to 'Edit', edit_top_path(@top) %> |
<%= link_to 'Back', tops_path %>